services:
  liquibase:
    image: liquibase/liquibase:4.25
    volumes:
      - ./src/main/resources/changelog:/liquibase/changelog
    working_dir: /liquibase
    command: [
      "--changeLogFile=changelog/master.xml",
      "--url=jdbc:postgresql://postgres:5432/mydatabase",
      "--username=postgres", 
      "--password=password",
      "update"
    ]
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["migration"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: