FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN DATABASE_URL="postgresql://postgres:postgres@localhost:5432/oppsdb?schema=public" npx prisma generate

EXPOSE 8080

CMD ["npm", "run", "start"]