# Сборка фронтенда
FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# На этом всё, nginx будет отдавать статику, поэтому production stage тут не нужен
